on:
  workflow_call:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: wait-job
        run: sleep 10s
        shell: bash
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Retrieve Version
        id: tagVersion
        run: |
          echo "version=$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' lerna.json)"
          echo "version=$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' lerna.json)" >> "$GITHUB_OUTPUT"
      - name: Tag version
        run: |
          git config user.name github-actions
          git config user.email noreply@github.com
          git tag -a v$VERSION_NUMBER -m "v$VERSION_NUMBER"
          git push origin v$VERSION_NUMBER --no-verify
        env:
          VERSION_NUMBER: ${{ steps.tagVersion.outputs.version }}